version: '3'
services:
  nginx:
    image: nginx:1.13.2
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: always
    environment:
      - NGINX_UPSTREAM=http://app:8000
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  app:
    build: .
    image: 127.0.0.1:5000/orangain/python-app
    # ports:
    #  - "8000:8000"
    environment:
      - ES_HOSTS=elasticsearch:9200
      - TZ=Asia/Tokyo
    depends_on:
      - elasticsearch
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  esdata1:
    driver: local
